server:
  port: 8800
spring:
  application:
    name: Bulletin_board
  datasource:
    url: jdbc:postgresql://localhost:5432/bulletin_kotlin
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  key: weqjfnqbewfoi2371432yogr8qfwwgefb1ffh17803gf18g34fbasdsaf134fqf
  access-token-expiration: 120000
  refresh-token-expiration: 360000